### PR TITLE
allow safe ^2.0

### PR DESCRIPTION
**Pull request by lemorragia**
homogeneity in the require loop "solido/php-coding-standards" -> "solido/phpstan-rules" -> "kcs/class-finder" -> "solido/php-coding-standards"

### CODE REVIEW

**Comment by alekitto** [comment]
Please also update `composer.lock` file

**Comment by lemorragia** [comment]
> Please also update `composer.lock` file

done!

**Comment by alekitto** [comment]
Could you check the tests failures?
It seems that the new version of `safe` removed the `uasort` function...

**Comment by lemorragia** [comment]
will do

**Review by alekitto — APPROVED** [review]

**Pull request merged**
